# kubectl create -f server-side-dep.yaml

# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-side-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-side-app
  template:
    metadata:
      labels:
        app: server-side-app
    spec:
      containers:
      - name: server-side-container
        image: msgarshasbi/server-side-simulator:v1
        ports:
        - containerPort: 3000

